import { collectFacts, removedLine } from "./facts.mjs";
import { esc, listPhrase, plural, writeText } from "./lib.mjs";

const facts = collectFacts();
const marker = "<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->";
// Name template skills that are not installed, so the README says why they are absent.
const header = facts.removed.length ? `${marker}
${removedLine(facts.removed)}` : marker;

// Group counts with empty groups left out: "7 core", "13 discipline", "14 specialist".
const groupCounts = facts.groups.filter((group) => facts.tierCounts[group.id] > 0).map((group) => `${facts.tierCounts[group.id]} ${group.id}`);

// Prose that names a skill only when the skill is installed, so a project that removed
// skills never advertises them. With every template skill present the text is unchanged.
const has = (name) => facts.inventoryNames.includes(name);

function pluginTry() {
  const examples = [["recall", "`/claude-starter:recall`"], ["brainstorming", "`/claude-starter:brainstorming plan the next feature`"]]
    .filter(([name]) => has(name)).map(([, text]) => text);
  return examples.length ? `Then try ${examples.join(" or ")}. ` : "";
}

function templateStep() {
  return has("init-project")
    ? "clone the new repository, then run Claude Code's `/init-project` command or ask Codex to use the `init-project` skill."
    : "clone the new repository, then follow the [setup guide](GUIDE.md#full-template).";
}

function recallStep() {
  return has("recall") ? " Then ask Claude Code or Codex to use `recall` before the first unfamiliar change." : "";
}

function either(parts, joiner = "; ") {
  return parts.filter(Boolean).join(joiner);
}

function addsTable() {
  const reviews = facts.inventoryNames.some((name) => name.endsWith("review"));
  const rows = [
    has("recall") && "| Remember the project | `recall` loads relevant committed facts, decisions, and pitfalls before unfamiliar work |",
    has("long-horizon") && "| Finish sustained work | `long-horizon` records progress and evidence across bounded rounds, with fresh audit context |",
    reviews && "| Challenge a result | Independent and cross-vendor review skills check work through available agents or authenticated CLIs |",
    (has("fable-mode") || has("perf-loop")) && `| Verify a claim | ${either([
      has("fable-mode") && "`fable-mode` separates current-state, change, and causal claims and returns a verdict",
      has("perf-loop") && "`perf-loop` measures optimization against a baseline",
    ])} |`,
    has("addskill") && "| Maintain skills | `addskill` handles creating, importing, updating, and installing skills with the resources each runtime needs |",
    (has("refine") || has("sync-starter")) && `| Improve the workflow | ${either([
      has("refine") && "`refine` captures observed friction",
      has("sync-starter") && "`sync-starter` carries selected generic fixes between repositories",
    ])} |`,
  ].filter(Boolean);
  if (!rows.length) return "";
  return `## what the firmware adds

| Need | Workflow built into the repository |
| --- | --- |
${rows.join("\n")}

These are agent instructions and supporting tools. Structural checks validate the package; actual execution still needs the appropriate model, tools, credentials, and evidence.

`;
}

const refineLine = has("refine")
  ? "`refine` turns observed friction into a small, reviewable change that strengthens the repository before the next task begins."
  : "Observed friction becomes a small, reviewable change that strengthens the repository before the next task begins.";
const syncLine = has("sync-starter")
  ? "The dotted branch is separate: after human review, `sync-starter` can move a generic improvement into the template so future repositories begin with it."
  : "The dotted branch is separate: after human review, a generic improvement can move into the template so future repositories begin with it.";

function picture(name, alt) {
  return `<picture>
<source media="(max-width: 500px) and (prefers-color-scheme: dark)" srcset="assets/readme/${name}-narrow-dark.svg">
<source media="(max-width: 500px)" srcset="assets/readme/${name}-narrow-light.svg">
<source media="(prefers-color-scheme: dark)" srcset="assets/readme/${name}-dark.svg">
<img alt="${esc(alt)}" src="assets/readme/${name}-light.svg" width="100%">
</picture>`;
}

function skillLists() {
  const sections = facts.groups.filter((group) => facts.tierCounts[group.id] > 0).map((group) => {
    const skills = facts.skills.filter((skill) => skill.group === group.id);
    const rows = skills.map((skill) => `- [\`${skill.name}\`](.claude/skills/${skill.name}/SKILL.md) · ${skill.description}`).join("\n");
    return `### ${group.label.toLowerCase()} · ${skills.length}\n\n${rows}`;
  }).join("\n\n");
  return `<!-- skill-list:start -->\n${sections}\n<!-- skill-list:end -->`;
}

const readme = `${header}

${picture("boot", `Harness Firmware boots with ${plural(facts.skillCount, "skill")}, ${plural(facts.referenceFileCount, "project-memory file")}, and ${plural(facts.runtimeCount, "runtime boundary", "runtime boundaries")} ready.`)}

A repository starter for **Claude Code and Codex**. Harness Firmware gives both agents versioned instructions, durable project memory, reusable skills, and workflows for testing and independent review.

Keep project decisions and pitfalls with the code. Carry useful lessons into the next session. Review changes before carrying them into another repository.

[Install the skills or start a repository](#quickstart).

## quickstart

Use the **skills-only plugin** for an existing Claude Code repository. Use the **full template** for a new repository or Codex support.

### existing repository · Claude Code plugin

Run these commands inside Claude Code:

\`\`\`text
/plugin marketplace add ryanportfolio/Harness-Firmware
/plugin install claude-starter@claude-starter
\`\`\`

${pluginTry()}Plugin skills use the \`claude-starter\` namespace.

### new repository · full template

Create a repository with the kernel, hooks, committed memory, skills, and synchronization tools:

- GitHub: select **Use this template**, ${templateStep()}
- From a cloned Harness Firmware checkout on macOS or Linux: \`bash bootstrap/new-claude-project.sh --name my-app --dest ~/code\`
- From a cloned checkout on Windows: double-click \`bootstrap/New-ClaudeProject.cmd\`.

In the created repository, run \`node .claude/scripts/doctor.mjs\`. Success means the doctor reports no failures.${recallStep()}

[Open the complete setup guide](GUIDE.md#full-template) · [View validation runs](https://github.com/ryanportfolio/Harness-Firmware/actions/workflows/validate-template.yml)

${addsTable()}## the repository feedback loop

${picture("feedback", "Recall, work, verify, refine, and a reviewed repository change form a local loop. A separate human-approved sync can carry generic changes into future repositories.")}

The everyday loop is **recall → work → verify → refine → reviewed repository change → next task**. Project facts load before unfamiliar work. Verification captures evidence. ${refineLine}

${syncLine} Keeping the lesson local remains the default.

## two runtimes, explicit ownership

${picture("runtime", `${plural(facts.skillCount, "Claude Code skill")} and ${plural(facts.codexSkillCount, "Codex skill")} share project memory. Codex has ${plural(facts.codexNativeCount, "native workflow")}.`)}

**${plural(facts.skillCount, "Claude Code skill")} · ${plural(facts.codexSkillCount, "Codex skill")} · ${plural(facts.codexNativeCount, "native Codex workflow")}**

- **Claude Code:** reads \`CLAUDE.md\`, \`.claude/skills/\`, and hooks for canonical playbooks and Claude-specific startup behavior.
- **Codex:** reads \`AGENTS.md\` and \`.agents/skills/\` for standalone Codex workflows with explicit capability and safety boundaries; every Claude skill has a maintained native Codex version or is disabled for Codex. [Skill ownership and personal copies](docs/codex-skills.md) explains how they are maintained.

Both runtimes read the committed project topics under \`.claude/reference/\`. Shared workflows live under \`.claude/skills/\`; standalone Codex workflows live under \`.agents/skills/\`.

## ${plural(facts.skillCount, "workflow")}, loaded when called

**${groupCounts.join(" · ")}**

Only names and routing descriptions sit in the repository's generated skill index. Full workflow bodies stay on demand. The diagram's byte figures are a repository source-file estimate, not total runtime context; [the guide documents the measurement](GUIDE.md#measure-the-always-loaded-layer).

<details>
<summary><strong>Click to open the generated skill memory map</strong></summary>

${picture("skills", `A memory map of ${plural(facts.skillCount, "on-demand workflow")} grouped into ${listPhrase(groupCounts)} ${facts.skillCount === 1 ? "skill" : "skills"}.`)}

</details>

<details>
<summary><strong>Click to browse ${facts.skillCount === 1 ? "the only skill" : `all ${facts.skillCount} skills`}</strong></summary>

${skillLists()}

</details>

## checked on every change

The validation workflow checks shell and PowerShell entry points, Codex skill registration and drift from the Claude source, native skill propagation, linked skill resources, retired entrypoints, the Windows project generator, and this README's generated facts and assets. [Inspect the CI runs](https://github.com/ryanportfolio/Harness-Firmware/actions/workflows/validate-template.yml).

[\`.agents/skill-modes.json\`](.agents/skill-modes.json) records which skills have a native Codex version and which are disabled for Codex. [Maintenance guidance](docs/codex-skills.md) covers native updates, disabled skills, and personal copies.

Run the local health check:

\`\`\`bash
node .claude/scripts/doctor.mjs
\`\`\`

## documentation

- [Setup and operating guide](GUIDE.md)
- [Contribution process](CONTRIBUTING.md)
- [Release history](CHANGELOG.md)
- [Skill provenance](.claude/skills/PROVENANCE.md)
- [MIT license](LICENSE)
`;

writeText("README.md", readme);
process.stdout.write("Generated README.md.\n");
